name: Build and Push ECR Image - Quick

on:
  #push:
  #  paths:
  #    #- "API/**"
  #  branches:
  #    - main
  workflow_dispatch: {}

env:
  OCTOPUS_URL: https://wrg.octopus.app
  OCTOPUS_SERVICE_ACCOUNT: b45a10cc-1380-480d-ab25-28e36d54cd63
  OCTOPUS_SPACE: New Cascadia Imports
  ECR_ROLE_TO_ASSUME: arn:aws:iam::381713788115:role/ryanrousseau-github-org
  ECR_SESSION_NAME: githubworkflow
  ECR_REGION: us-west-2
  ECR_URL: 381713788115.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: demo/demoapp-prime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Version Number
        id: version-generator
        run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER-quick" >> $GITHUB_OUTPUT

      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ env.OCTOPUS_URL }}
          service_account_id: ${{ env.OCTOPUS_SERVICE_ACCOUNT }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ECR_ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ECR_SESSION_NAME }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push to ECR
        uses: docker/build-push-action@v4
        with:
          context: ./API/
          file: ./API/Dockerfile
          push: true
          platforms: linux/x86_64
          provenance: false
          sbom: false
          tags: |
            ${{ env.ECR_URL }}/${{ env.ECR_REPOSITORY }}:${{ steps.version-generator.outputs.version }}

      - uses: OctopusDeploy/push-build-information-action@v3
        name: Push Build Information 🐙
        with:
          version: ${{ steps.version-generator.outputs.version }}
          packages: |
            ${{ env.ECR_REPOSITORY }}
