name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Version Number
      id: version-generator
      run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::381713788115:role/ryanrousseau-github-org
        role-session-name: githubworkflow
        aws-region: us-west-2

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./DemoApp/
        file: ./DemoApp/Dockerfile
        push: true
        platforms: linux/arm64
        provenance: false
        sbom: false
        tags: |
            octopussolutionsengineering/demoapp-prime:${{ steps.version-generator.outputs.version }}
            381713788115.dkr.ecr.us-west-2.amazonaws.com/demo/demoapp-prime:${{ steps.version-generator.outputs.version }}
